import type { Sermon } from "@/types";
import { thumb } from "@/lib/media";

const CHANNEL = "https://www.youtube.com/@prophetpromiseministries4267";

function yt(id: string) {
  return `https://www.youtube.com/watch?v=${id}`;
}

/**
 * Verified sermon data — real titles, real publish dates, real durations,
 * sourced from VOBI's official YouTube channel (docs/vobi-research.md §7.2).
 * Speaker is taken from VOBI's own title convention
 * "Sermon | <Title> | Prophet Promise".
 */
export const seedSermons: Sermon[] = [
  {
    id: "MIj5Em8soV0",
    slug: "power-in-the-mouth",
    title: "Power In The Mouth",
    speaker: "Prophet Promise",
    date: "2026-10-01",
    thumbnail: thumb("MIj5Em8soV0"),
    youtubeUrl: yt("MIj5Em8soV0"),
    category: "sermon",
    durationSeconds: 3636,
    views: 151,
  },
  {
    id: "yBesC26mSSA",
    slug: "calmness-brings-victory-over-temptation",
    title: "Calmness Brings Victory Over Temptation",
    speaker: "Prophet Promise",
    date: "2026-09-15",
    thumbnail: thumb("yBesC26mSSA"),
    youtubeUrl: yt("yBesC26mSSA"),
    category: "sermon",
    durationSeconds: 3887,
    views: 248,
  },
  {
    id: "VY_YMo1UpGw",
    slug: "how-to-get-your-prayers-answered-part-2",
    title: "How to get your prayers answered — Part 2",
    speaker: "Prophet Promise",
    date: "2026-09-08",
    thumbnail: thumb("VY_YMo1UpGw"),
    youtubeUrl: yt("VY_YMo1UpGw"),
    category: "sermon",
    durationSeconds: 1894,
    views: 187,
  },
  {
    id: "5hR5RpDJ0GA",
    slug: "how-to-get-your-prayers-answered",
    title: "How to get your prayers answered",
    speaker: "Prophet Promise",
    date: "2026-08-26",
    thumbnail: thumb("5hR5RpDJ0GA"),
    youtubeUrl: yt("5hR5RpDJ0GA"),
    category: "sermon",
    durationSeconds: 4360,
    views: 259,
  },
  {
    id: "pWvcKKfaXPs",
    slug: "wake-up-and-protect-your-destiny",
    title: "Wake up and protect your destiny",
    speaker: "Prophet Promise",
    date: "2026-08-19",
    thumbnail: thumb("pWvcKKfaXPs"),
    youtubeUrl: yt("pWvcKKfaXPs"),
    category: "sermon",
    durationSeconds: 3086,
    views: 147,
  },
  {
    id: "sF7fpb43VaM",
    slug: "do-not-submit-to-your-situation",
    title: "Don't Submit To Your Situation",
    speaker: "Prophet Promise",
    date: "2026-07-28",
    thumbnail: thumb("sF7fpb43VaM"),
    youtubeUrl: yt("sF7fpb43VaM"),
    category: "sermon",
    durationSeconds: 1798,
    views: 184,
  },
  {
    id: "78sc4pcwrHA",
    slug: "the-dangers-of-familiarity",
    title: "The Dangers of Familiarity",
    speaker: "Prophet Promise",
    date: "2026-07-22",
    thumbnail: thumb("78sc4pcwrHA"),
    youtubeUrl: yt("78sc4pcwrHA"),
    category: "sermon",
    durationSeconds: 2522,
    views: 136,
  },
  {
    id: "i9S_xErFgiM",
    slug: "god-expects-us-to-grow-through-our-trials",
    title: "God expects us to grow through our trials",
    speaker: "Prophet Promise",
    date: "2026-07-15",
    thumbnail: thumb("i9S_xErFgiM"),
    youtubeUrl: yt("i9S_xErFgiM"),
    category: "sermon",
    durationSeconds: 3505,
    views: 196,
  },
  {
    id: "eZEP0xzN310",
    slug: "he-is-a-loving-god",
    title: "He Is A Loving God",
    speaker: "Prophet Promise",
    date: "2026-07-10",
    thumbnail: thumb("eZEP0xzN310"),
    youtubeUrl: yt("eZEP0xzN310"),
    category: "sermon",
    durationSeconds: 1984,
    views: 125,
  },
  {
    id: "4GDAFRBqwMw",
    slug: "serve-god-by-his-spirit",
    title: "Serve God by His Spirit",
    speaker: "Prophet Promise",
    date: "2026-06-23",
    thumbnail: thumb("4GDAFRBqwMw"),
    youtubeUrl: yt("4GDAFRBqwMw"),
    category: "sermon",
    durationSeconds: 2617,
    views: 231,
  },
  {
    id: "5X2ZHrLffyI",
    slug: "avoid-the-trap-of-looking-back",
    title: "Avoid The Trap Of Looking Back",
    speaker: "Prophet Promise",
    date: "2026-06-17",
    thumbnail: thumb("5X2ZHrLffyI"),
    youtubeUrl: yt("5X2ZHrLffyI"),
    category: "sermon",
    durationSeconds: 3622,
    views: 242,
  },
  {
    id: "3qBpqouObcY",
    slug: "if-god-has-said-it-no-one-can-stop-it",
    title: "If God has said it no one can stop it",
    speaker: "Prophet Promise",
    date: "2026-05-21",
    thumbnail: thumb("3qBpqouObcY"),
    youtubeUrl: yt("3qBpqouObcY"),
    category: "sermon",
    durationSeconds: 5213,
    views: 168,
  },
  {
    id: "6Gvt6NEAeJY",
    slug: "power-of-imagination",
    title: "Power Of Imagination",
    speaker: "Prophet Promise",
    date: "2026-05-14",
    thumbnail: thumb("6Gvt6NEAeJY"),
    youtubeUrl: yt("6Gvt6NEAeJY"),
    category: "sermon",
    durationSeconds: 4694,
    views: 247,
  },
  {
    id: "AeL-g0-o0u8",
    slug: "power-of-resurrection",
    title: "Power of Resurrection",
    speaker: "Prophet Promise",
    date: "2026-04-29",
    thumbnail: thumb("AeL-g0-o0u8"),
    youtubeUrl: yt("AeL-g0-o0u8"),
    category: "sermon",
    durationSeconds: 6666,
    views: 158,
  },
  {
    id: "bpW3XpLAcok",
    slug: "fruitful-vine",
    title: "Fruitful Vine",
    speaker: "Prophet Promise",
    date: "2026-03-26",
    thumbnail: thumb("bpW3XpLAcok"),
    youtubeUrl: yt("bpW3XpLAcok"),
    category: "sermon",
    durationSeconds: 6616,
    views: 197,
  },
  {
    id: "sInoJId6apc",
    slug: "ministering-spirits-angels-of-god-part-1",
    title: "Ministering Spirits (Angels of God) — Part 1",
    speaker: "Prophet Promise",
    date: "2026-03-11",
    thumbnail: thumb("sInoJId6apc"),
    youtubeUrl: yt("sInoJId6apc"),
    category: "teaching",
    durationSeconds: 4991,
    views: 182,
  },
  {
    id: "ycsBRmf6P6k",
    slug: "idol-worship-in-the-heart",
    title: "Idol worship in the Heart",
    speaker: "Prophet Promise",
    date: "2026-03-04",
    thumbnail: thumb("ycsBRmf6P6k"),
    youtubeUrl: yt("ycsBRmf6P6k"),
    category: "sermon",
    durationSeconds: 5047,
    views: 117,
  },
  {
    id: "tfTPnpbrqpk",
    slug: "interpreting-times-and-seasons",
    title: "Interpreting Times and Seasons",
    speaker: "Prophet Promise",
    date: "2026-02-11",
    thumbnail: thumb("tfTPnpbrqpk"),
    youtubeUrl: yt("tfTPnpbrqpk"),
    category: "sermon",
    durationSeconds: 4430,
    views: 335,
  },
  {
    id: "NblpmxogXjM",
    slug: "no-competition-in-destiny",
    title: "No Competition in Destiny",
    speaker: "Prophet Promise",
    date: "2026-02-05",
    thumbnail: thumb("NblpmxogXjM"),
    youtubeUrl: yt("NblpmxogXjM"),
    category: "sermon",
    durationSeconds: 2540,
    views: 113,
  },
  {
    id: "ictNkEfgU3Y",
    slug: "learn-from-those-who-have-made-it",
    title: "Learn from those who have made it",
    speaker: "Prophet Promise",
    date: "2026-01-20",
    thumbnail: thumb("ictNkEfgU3Y"),
    youtubeUrl: yt("ictNkEfgU3Y"),
    category: "sermon",
    durationSeconds: 3936,
    views: 110,
  },
  {
    id: "9iV-U9pxUvs",
    slug: "a-new-dream",
    title: "A New Dream",
    speaker: "Prophet Promise",
    date: "2026-01-06",
    thumbnail: thumb("9iV-U9pxUvs"),
    youtubeUrl: yt("9iV-U9pxUvs"),
    category: "special",
    durationSeconds: 739,
    views: 205,
  },
  {
    id: "-RzhuM5lPBE",
    slug: "speak-faith",
    title: "Speak Faith",
    speaker: "Prophet Promise",
    date: "2025-11-20",
    thumbnail: thumb("-RzhuM5lPBE"),
    youtubeUrl: yt("-RzhuM5lPBE"),
    category: "sermon",
    durationSeconds: 2249,
    views: 142,
  },
];

/** Verified live services — real dates and durations (research §7.3). */
export const seedServices: Sermon[] = [
  {
    id: "zS8NL8NMNlQ",
    slug: "sunday-live-service-04-october-2026",
    title: "Sunday Live Service — 04 October 2026",
    speaker: "Prophet Promise",
    date: "2026-10-04",
    thumbnail: thumb("zS8NL8NMNlQ"),
    youtubeUrl: yt("zS8NL8NMNlQ"),
    category: "service",
    durationSeconds: 23499,
    views: 946,
  },
  {
    id: "KRoODbK1al8",
    slug: "sunday-live-service-27-september-2026",
    title: "Sunday Live Service — 27 September 2026",
    speaker: "Prophet Promise",
    date: "2026-09-27",
    thumbnail: thumb("KRoODbK1al8"),
    youtubeUrl: yt("KRoODbK1al8"),
    category: "service",
    durationSeconds: 26667,
    views: 1233,
  },
  {
    id: "RQYNQSq-tFU",
    slug: "sunday-service-06-september-2026",
    title: "Sunday Service — 06 September 2026",
    speaker: "Prophet Promise",
    date: "2026-09-07",
    thumbnail: thumb("RQYNQSq-tFU"),
    youtubeUrl: yt("RQYNQSq-tFU"),
    category: "service",
    durationSeconds: 11643,
    views: 858,
  },
  {
    id: "7PQllxO7OWQ",
    slug: "sunday-live-service-16-august-2026",
    title: "Sunday Live Service — 16 August 2026",
    speaker: "Prophet Promise",
    date: "2026-08-16",
    thumbnail: thumb("7PQllxO7OWQ"),
    youtubeUrl: yt("7PQllxO7OWQ"),
    category: "service",
    durationSeconds: 26999,
    views: 725,
  },
  {
    id: "GiScarDvZec",
    slug: "live-from-victoria-falls",
    title: "Live from Victoria Falls, Zimbabwe — VOBI Sunday Service with Prophet Promise",
    speaker: "Prophet Promise",
    date: "2025-06-01",
    thumbnail: thumb("GiScarDvZec"),
    youtubeUrl: yt("GiScarDvZec"),
    category: "service",
    durationSeconds: 34426,
    views: 421,
    description:
      "We welcome you to our Sunday service with Prophet Promise. As we gather in one spirit, let us quiet our hearts and prepare to connect deeply with our Heavenly Father through worship and prayer.",
  },
  {
    id: "u-fmfu7Kov0",
    slug: "healing-big-sunday-mass-prayer",
    title: "There's a Spirit Behind! Healing Big Sunday Mass Prayer",
    speaker: "Prophet Promise",
    date: "2026-06-18",
    thumbnail: thumb("u-fmfu7Kov0"),
    youtubeUrl: yt("u-fmfu7Kov0"),
    category: "special",
    durationSeconds: 716,
    views: 357,
  },
  {
    id: "MdM0beIv8Ok",
    slug: "mercy-land-sunday-service-20-september-2026",
    title: "Mercy Land Sunday Service — 20 September 2026",
    speaker: "Prophet Promise",
    date: "2026-09-20",
    thumbnail: thumb("MdM0beIv8Ok"),
    youtubeUrl: yt("MdM0beIv8Ok"),
    category: "service",
    durationSeconds: 1800,
    views: 234,
  },
  {
    id: "-lt-j9iBDx4",
    slug: "the-night-of-exodus-2025-2026",
    title: "The Night of Exodus 2025-26 — Crossover Candlelight Service",
    speaker: "Prophet Promise",
    date: "2025-12-31",
    thumbnail: thumb("-lt-j9iBDx4"),
    youtubeUrl: yt("-lt-j9iBDx4"),
    category: "special",
  },
  {
    id: "aCLyo-8DdaM",
    slug: "week-for-testimonies-mass-prayer",
    title: "May this week be a week for testimonies — Mass Prayer",
    speaker: "Prophet Promise",
    date: "2025-10-01",
    thumbnail: thumb("aCLyo-8DdaM"),
    youtubeUrl: yt("aCLyo-8DdaM"),
    category: "special",
  },
];

export const sermonCategories = [
  { key: "sermon", label: "Sermons" },
  { key: "teaching", label: "Teachings" },
  { key: "service", label: "Services" },
  { key: "special", label: "Special Services" },
] as const;

export const channelUrl = CHANNEL;
