export type TvCat = "testimony" | "prophecy" | "massprayer" | "praise" | "funny";

export const tvLabels: Record<string, string> = {
  sermons: "Sermon", testimony: "Testimony", prophecy: "Prophecy", massprayer: "Mass Prayer", praise: "Praise & Worship", funny: "Funny Moment",
};

export const tvItems: { id: string; title: string; cat: TvCat }[] = [
  { id: "m4D9MKtUcMY", title: "powerful testimony", cat: "testimony" },
  { id: "SNv3xXzyN3w", title: "What was impossible turned into testimony!", cat: "testimony" },
  { id: "9UxTQ3DVNug", title: "Believe In God and He will Give You Favor | Testimony | Prophet Promise", cat: "testimony" },
  { id: "Ifqx-z6iz1I", title: "The God Of Wonders | Testimony | Prophet Promise", cat: "testimony" },
  { id: "_6MW4hS7S6Y", title: "Divine Turn Around | Deliverance | Testimony", cat: "testimony" },
  { id: "C6UfxTr87IY", title: "You Shall Testify!!! | Testimony | Prophet Promise", cat: "testimony" },
  { id: "bb8QwYAt23w", title: "Promoted by God's grace | Testimony | Prophet Promise", cat: "testimony" },
  { id: "_rkYsm6YjSc", title: "God's love breaks chains!!! | Testimony#testimony #deliverance #prophetpromise", cat: "testimony" },
  { id: "9OskKl7EDJU", title: "Exposed by the Anointing: A Testimony of True Freedom", cat: "testimony" },
  { id: "qe2NjJzK4B4", title: "Powerful Testimony of God's Unrelenting Love and Grace", cat: "testimony" },
  { id: "RyeE1nU4_Fw", title: "He Almost Walked Out Until This Happened! | Testimony | VOBI Ministries", cat: "testimony" },
  { id: "DS9f7-iHV1Q", title: "With God All things Are Possible | Testimony | Prophet Promise", cat: "testimony" },
  { id: "ONCBCkR3Oyk", title: "l see a man behind you!!! | Testimony | Prophet Promise", cat: "testimony" },
  { id: "lru3wHJZ1gw", title: "Grateful For Divine Healing | Testimony | Prophet Promise", cat: "testimony" },
  { id: "FC8UrxtmbyU", title: "When God takes the wheel, you can trust the journey | Testimony", cat: "testimony" },
  { id: "E_xMdm4Na2w", title: "Trusting God's Timing | Testimony | Prophet Promise", cat: "testimony" },
  { id: "CA1xCvjeHsI", title: "Powerful Testimony of God's mantles.", cat: "testimony" },
  { id: "apczP4do-rw", title: "By the grace of God, I made it through | Testimony | Prophet Promise", cat: "testimony" },
  { id: "IQDP3raMJN8", title: "Faith On Wheels! | Testimony | Prophet Promise", cat: "testimony" },
  { id: "oMgVRDHyV0k", title: "There is Power In The Anointed Mantles | Testimony | Prophet Promise", cat: "testimony" },
  { id: "ApMH-zdmlmk", title: "Have faith In God | Testimony | Prophet Promise", cat: "testimony" },
  { id: "7n170bVa_4A", title: "The Enemy's Trap Exposed | Testimony | Prophet Promise", cat: "testimony" },
  { id: "dKP7z3quXuY", title: "Precious gift from above | Testimony | Prophet Promise", cat: "testimony" },
  { id: "-aooWE6RuOI", title: "As you celebrate this testimony yours is Loading in Jesus name.", cat: "testimony" },
  { id: "-G24aIGCWg8", title: "From a prophetic signature to 21 days of non-stop breakthroughs!", cat: "prophecy" },
  { id: "BRh2HGu3JGk", title: "Prophetic Moments with Prophet Promise | VOBI MINISTRIES", cat: "prophecy" },
  { id: "qmf-1nkJXTs", title: "The Word is alive!!! Witnessing the convergence of prophecies God's faithfulness woven through time.", cat: "prophecy" },
  { id: "vKqxWpTX8UE", title: "I prophesy you... You will struggle no more!!!", cat: "prophecy" },
  { id: "yw75KUyV1FQ", title: "Sermon | Prophetic Declarations | Prophet Promise", cat: "prophecy" },
  { id: "pn9m8tib5Qc", title: "I prophesy you as a servant of Jesus Christ, your pockets will never run dry, money", cat: "prophecy" },
  { id: "XoK3vR7gyS4", title: "YOU ARE SUPPOSED TO BE TRAVELLING | PROPHECY TIME", cat: "prophecy" },
  { id: "5JvAVnMVUDg", title: "THEY'RE EATING YOUR CHILDREN | PROPHECY TIME", cat: "prophecy" },
  { id: "gBKY5yg3RSA", title: "AN ANGEL VISITED YOU! | PROPHECY TIME", cat: "prophecy" },
  { id: "kDitBXOp3BE", title: "God Reveals To Redeem | Prophet Promise#propheticword #ProphetPromise #vobiministries", cat: "prophecy" },
  { id: "DxlxaiXtY54", title: "Deliverance | Prophecy | Prophet Promise", cat: "prophecy" },
  { id: "1QhcQQkSH08", title: "A Prophetic Declaration For You | Prophet Promise", cat: "prophecy" },
  { id: "7igzmVujpds", title: "Sermon | Purpose of Prophecy | Prophet Promise", cat: "prophecy" },
  { id: "pa3QFGtLTpo", title: "A Prophetic Prayer For You | Mass Prayer | Prophet Promise", cat: "prophecy" },
  { id: "QDGOjiZQuzw", title: "''I prophesy you, No more lack in your life'' | Mass Prayer | Prophet Promise", cat: "prophecy" },
  { id: "D-qCfoIaNmY", title: "Prophecy Fulfilled through Faith and Overseas Blessing! | Testimony | Prophet Promise", cat: "prophecy" },
  { id: "f_2I9vkjEDg", title: "WHY YOU NEED TO FORGIVE | PROPHECY | PROPHET PROMISE", cat: "prophecy" },
  { id: "DTrQljRd_Jg", title: "Prophecies | Deliverance | Prophet Promise", cat: "prophecy" },
  { id: "DaA6zsfvyKk", title: "ADOPT JESUS | PROPHECY | PROPHET PROMISE MINISTRIES", cat: "prophecy" },
  { id: "9wJiA9CMcWw", title: "THE POWER OF PROPHECY| PROPHET PROMISE", cat: "prophecy" },
  { id: "lNz9H3GWwMY", title: "YOU HAVE STAYED TOO LONG IN THAT MOUNTAIN | PROPHETIC DECLARATION | PROPHET PROMISE", cat: "prophecy" },
  { id: "vmS0fWEvYfw", title: "PROPHECY AND DELIVERANCE", cat: "prophecy" },
  { id: "TOSf0M9nmLY", title: "THIS PROPHECY IS FOR YOU", cat: "prophecy" },
  { id: "iX_J7AB1Cyg", title: "Prophecy Time And Deliverance with Prophet Promise", cat: "prophecy" },
  { id: "WmrJujoEe1s", title: "Holy Spirit touch my case file | Mass Prayer | Prophet Promise", cat: "massprayer" },
  { id: "u-fmfu7Kov0", title: "There's a Spirit Behind! Healing Big Sunday Mass Prayer", cat: "massprayer" },
  { id: "mk70BpVKZD8", title: "One on One with Jesus | A Moment of Mass Prayer with Prophet Promise", cat: "massprayer" },
  { id: "-Tis_jQTUGs", title: "Mass Prayer | You are a Torchbearer! | Prophet Promise", cat: "massprayer" },
  { id: "7fMYrZ4OWVU", title: "Any spirit of infirmity in your life. be cut off! | Mass Prayer", cat: "massprayer" },
  { id: "_VjwgggFS2M", title: "''I Cancel Any Negative Dream Upon Your Life'' | Mass Prayer | Prophet Promise", cat: "massprayer" },
  { id: "cV5BXwEHVXY", title: "YOUR DAY OF APPOINTMENT WITH JESUS CHRIST! | VOBI Mass Prayer | 25 May 2025", cat: "massprayer" },
  { id: "DK3mwOmedwU", title: "I command that chameleon spirit out of your life | Mass Prayer | Prophet Promise", cat: "massprayer" },
  { id: "5SXyYXsgxAc", title: "''May your business shift to another level'' | Mass Prayer | Prophet Promise", cat: "massprayer" },
  { id: "EToFC6EfbsY", title: "Game Over! the enemy have lost the battle | Mass Prayer Prophet Promise", cat: "massprayer" },
  { id: "In1JffYoZ2Q", title: "MASS PRAYER WITH PROPHET PROMISE | SUN JAN 12, 2025", cat: "massprayer" },
  { id: "DhCBv3xJ0Gg", title: "''I Speak A Hedge Of Protection Over Your Life'' | Mass Prayer", cat: "massprayer" },
  { id: "48l1j79Lfv0", title: "Sunday 17 Nov 2024 | Mass Prayer | Prophet Promise", cat: "massprayer" },
  { id: "aCLyo-8DdaM", title: "May this week be a week for testimonies | Mass prayer | Prophet Promise", cat: "massprayer" },
  { id: "VNYojlXCkHY", title: "''That fear of starting little must go in the name of Jesus Christ'' | Mass Prayer | Prophet Promise", cat: "massprayer" },
  { id: "EO885DFjr6I", title: "''I pronounce a blessing upon your life'' | Mass Prayer | Prophet Promise", cat: "massprayer" },
  { id: "MPsXpzjHFRI", title: "''Lord Jesus you are the Healer'' | Mass Prayer | Prophet Promise", cat: "massprayer" },
  { id: "_eEN_sej8iI", title: "''Break that shell of unbelief'' | Mass Prayer | Prophet Promise", cat: "massprayer" },
  { id: "LDIlKHMQ_is", title: "''l Pray, the Lord will fulfill all your heart desire this year'' | Mass Prayer | Prophet Promise", cat: "massprayer" },
  { id: "LngobLTxrJk", title: "''The Lord bless you and keep you'' | Mass prayer | Prophet Promise", cat: "massprayer" },
  { id: "lvEKeMtN6sc", title: "''Receive good health in the name of Jesus Christ'' | Mass Prayer Sun 10 DEC 2023 | Prophet Promise", cat: "massprayer" },
  { id: "bG-RNRoxXkQ", title: "Be Released From That Anti-Marriage Spirit | Mass Prayer | Prophet Promise", cat: "massprayer" },
  { id: "o6Q569dfp10", title: "''Its your season to Bloom in the name of Jesus'' | Mass Prayer | Prophet Promise", cat: "massprayer" },
  { id: "3j-4bOnQfWI", title: "PUT YOUR DEMAND ON GOD'S ANOINTING | MASS PRAYER WITH PROPHET PROMISE", cat: "massprayer" },
  { id: "OT4oFQxMiwI", title: "YOU DIDN'T STOP AT THE STOP SIGN! | SHORT FILM", cat: "funny" },
  { id: "MB652eo4dpQ", title: "Prophet Promise Funny Moments Part 2 | Birthday Week Special!", cat: "funny" },
  { id: "cPPSu4C6xTI", title: "THIS MAN MADE EVERYONE LAUGH", cat: "funny" },
  { id: "RDklnXV9xEo", title: "ACTION BORN OF SPIRIT PART 1 | PROPHET PROMISE | FUNNY MOMENTS", cat: "funny" },
];
