// AUTO-GENERATED from client/public/media - official VOBI YouTube thumbnails
export const MEDIA: Record<string, string> = {
  "3qBpqouObcY": "/media/3qBpqouObcY-maxresdefault.jpg",
  "4GDAFRBqwMw": "/media/4GDAFRBqwMw-maxresdefault.jpg",
  "5hR5RpDJ0GA": "/media/5hR5RpDJ0GA-maxresdefault.jpg",
  "5Wfv7CF5gBA": "/media/5Wfv7CF5gBA-maxresdefault.jpg",
  "5X2ZHrLffyI": "/media/5X2ZHrLffyI-maxresdefault.jpg",
  "6Gvt6NEAeJY": "/media/6Gvt6NEAeJY-maxresdefault.jpg",
  "78sc4pcwrHA": "/media/78sc4pcwrHA-maxresdefault.jpg",
  "7PQllxO7OWQ": "/media/7PQllxO7OWQ-maxresdefault.jpg",
  "9iV-U9pxUvs": "/media/9iV-U9pxUvs-maxresdefault.jpg",
  "9UxTQ3DVNug": "/media/9UxTQ3DVNug-maxresdefault.jpg",
  "aCLyo-8DdaM": "/media/aCLyo-8DdaM-maxresdefault.jpg",
  "AeL-g0-o0u8": "/media/AeL-g0-o0u8-maxresdefault.jpg",
  "bb8QwYAt23w": "/media/bb8QwYAt23w-maxresdefault.jpg",
  "bpW3XpLAcok": "/media/bpW3XpLAcok-maxresdefault.jpg",
  "BRh2HGu3JGk": "/media/BRh2HGu3JGk-maxresdefault.jpg",
  "bul9y7wfBVs": "/media/bul9y7wfBVs-maxresdefault.jpg",
  "CA1xCvjeHsI": "/media/CA1xCvjeHsI-maxresdefault.jpg",
  "CXIu_vk8kAU": "/media/CXIu_vk8kAU-maxresdefault.jpg",
  "DS9f7-iHV1Q": "/media/DS9f7-iHV1Q-maxresdefault.jpg",
  "E_xMdm4Na2w": "/media/E_xMdm4Na2w-maxresdefault.jpg",
  "eZEP0xzN310": "/media/eZEP0xzN310-maxresdefault.jpg",
  "FC8UrxtmbyU": "/media/FC8UrxtmbyU-maxresdefault.jpg",
  "GiScarDvZec": "/media/GiScarDvZec-maxresdefault.jpg",
  "i9S_xErFgiM": "/media/i9S_xErFgiM-maxresdefault.jpg",
  "ictNkEfgU3Y": "/media/ictNkEfgU3Y-maxresdefault.jpg",
  "Ifqx-z6iz1I": "/media/Ifqx-z6iz1I-maxresdefault.jpg",
  "It-rck1txVQ": "/media/It-rck1txVQ-maxresdefault.jpg",
  "j_v5biVaiXI": "/media/j_v5biVaiXI-maxresdefault.jpg",
  "JEPx1WH3scc": "/media/JEPx1WH3scc-sddefault.jpg",
  "km9II2XvBiY": "/media/km9II2XvBiY-maxresdefault.jpg",
  "KRoODbK1al8": "/media/KRoODbK1al8-maxresdefault.jpg",
  "kTwA5AfQjwQ": "/media/kTwA5AfQjwQ-maxresdefault.jpg",
  "lru3wHJZ1gw": "/media/lru3wHJZ1gw-maxresdefault.jpg",
  "-lt-j9iBDx4": "/media/-lt-j9iBDx4-maxresdefault.jpg",
  "MdM0beIv8Ok": "/media/MdM0beIv8Ok-maxresdefault.jpg",
  "MIj5Em8soV0": "/media/MIj5Em8soV0-maxresdefault.jpg",
  "mk70BpVKZD8": "/media/mk70BpVKZD8-maxresdefault.jpg",
  "NblpmxogXjM": "/media/NblpmxogXjM-maxresdefault.jpg",
  "opQtQbHX7a0": "/media/opQtQbHX7a0-maxresdefault.jpg",
  "pWvcKKfaXPs": "/media/pWvcKKfaXPs-maxresdefault.jpg",
  "rcIBB2umX6M": "/media/rcIBB2umX6M-maxresdefault.jpg",
  "rq5c5VmX_6o": "/media/rq5c5VmX_6o-hqdefault.jpg",
  "RQYNQSq-tFU": "/media/RQYNQSq-tFU-maxresdefault.jpg",
  "RyeE1nU4_Fw": "/media/RyeE1nU4_Fw-maxresdefault.jpg",
  "-RzhuM5lPBE": "/media/-RzhuM5lPBE-maxresdefault.jpg",
  "sF7fpb43VaM": "/media/sF7fpb43VaM-maxresdefault.jpg",
  "sInoJId6apc": "/media/sInoJId6apc-maxresdefault.jpg",
  "tfTPnpbrqpk": "/media/tfTPnpbrqpk-maxresdefault.jpg",
  "u-fmfu7Kov0": "/media/u-fmfu7Kov0-maxresdefault.jpg",
  "VdifUDsVwJk": "/media/VdifUDsVwJk-maxresdefault.jpg",
  "wtGVNe2VVkQ": "/media/wtGVNe2VVkQ-maxresdefault.jpg",
  "Y3wO1-A8HRo": "/media/Y3wO1-A8HRo-maxresdefault.jpg",
  "yBesC26mSSA": "/media/yBesC26mSSA-maxresdefault.jpg",
  "ycsBRmf6P6k": "/media/ycsBRmf6P6k-maxresdefault.jpg",
  "z9tib6RxGqA": "/media/z9tib6RxGqA-maxresdefault.jpg",
  "zE2k51mc1B8": "/media/zE2k51mc1B8-maxresdefault.jpg",
  "zS8NL8NMNlQ": "/media/zS8NL8NMNlQ-maxresdefault.jpg",
};

export function thumb(id: string): string {
  return MEDIA[id] ?? `https://i.ytimg.com/vi/${id}/hqdefault.jpg`;
}
